steps:
  - name: gcr.io/cloud-builders.docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
      - .
      - "-f"
      - Dockerfile
    volumes:
      - name: "dist"
        path: "/dist"
    id: Build
