steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - run
      - "-v"
      - "/workspace/dist:/tmp/streamlit/lib/dist"
      - "gcr.io/blocks-gn-kamito/streamlit-healthz:0.0.1"
      - /bin/bash
      - /tmp/streamlit/package.sh
    id: Build
timeout: 1800s
artifacts:
  objects:
    location: "gs://gn-streamlit-archive/20210226001/"
    paths:
      - "/workspace/dist/*"
